// Opt-in shell isolation (--isolate-shells): wrapper generation, the env
// allowlist contract, the privilege fail-fast, and the doctor-style access
// check. All pure or filesystem-local, so none of these tests need root; the
// root-only e2e lives in isolated-shell.e2e.test.ts.

import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, test } from 'vitest'
import {
  buildIsolatedShellScript,
  checkIsolatedShellSetup,
  checkShellIsolationPrivileges,
  evaluateIsolatedShellAccess,
  ISOLATED_SHELL_FORWARD_ENV_NAMES,
  ISOLATED_SHELL_PATH,
  parseCapEffHex,
  resolveAgentAccount,
  resolveIsolationBinary,
  SETUID_SETGID_CAPABILITY_MASK,
  writeIsolatedShellWrapper,
  type IsolatedShellAccount,
} from './isolated-shell.js'

const account: IsolatedShellAccount = {
  username: 'roadie-agent',
  uid: 4242,
  gid: 4242,
  home: '/home/roadie-agent',
}

const wrapperInput = {
  setprivPath: '/usr/bin/setpriv',
  envPath: '/usr/bin/env',
  bashPath: '/usr/bin/bash',
  account,
}

const tempDirs: string[] = []
afterEach(() => {
  for (const dir of tempDirs.splice(0)) {
    fs.rmSync(dir, { recursive: true, force: true })
  }
})

function useTempDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'roadie-isolated-shell-'))
  tempDirs.push(dir)
  return dir
}

describe('buildIsolatedShellScript', () => {
  test('drops to the agent user and execs bash through an env -i allowlist', () => {
    const script = buildIsolatedShellScript(wrapperInput)
    expect(script).toMatchInlineSnapshot(`
      "#!/bin/bash
      # Generated by Roadie (--isolate-shells roadie-agent). Do not edit:
      # the bot rewrites this file on every OpenCode server start.
      # Runs the agent tool shell as an unprivileged user: setpriv drops to the
      # account below and env -i replaces the environment with a fixed allowlist,
      # so the OpenCode server's credentials never reach a tool shell.
      exec '/usr/bin/setpriv' --reuid=4242 --regid=4242 --init-groups --no-new-privs \\
        '/usr/bin/env' -i \\
        PATH='/usr/local/bin:/usr/bin:/bin' \\
        HOME='/home/roadie-agent' \\
        TERM="\${TERM:-dumb}" \\
        LANG="\${LANG:-C.UTF-8}" \\
        ROADIE_SESSION_ID="\${ROADIE_SESSION_ID-}" \\
        ROADIE_AGENT_TOKEN="\${ROADIE_AGENT_TOKEN-}" \\
        ROADIE_THREAD_ID="\${ROADIE_THREAD_ID-}" \\
        ROADIE_CHANNEL_ID="\${ROADIE_CHANNEL_ID-}" \\
        ROADIE_ACTOR_PLATFORM="\${ROADIE_ACTOR_PLATFORM-}" \\
        ROADIE_ACTOR_ID="\${ROADIE_ACTOR_ID-}" \\
        ROADIE_ACTOR_NAME="\${ROADIE_ACTOR_NAME-}" \\
        ROADIE_ACTOR_VIA="\${ROADIE_ACTOR_VIA-}" \\
        ROADIE_PERSON_ID="\${ROADIE_PERSON_ID-}" \\
        '/usr/bin/bash' "$@"
      "
    `)
  })

  test('passes the command arguments through to the inner bash', () => {
    const script = buildIsolatedShellScript(wrapperInput)
    expect(script.trimEnd().endsWith(`'/usr/bin/bash' "$@"`)).toBe(true)
  })

  test('never forwards credentials, secrets or provider keys', () => {
    const script = buildIsolatedShellScript(wrapperInput)
    const forbidden = [
      // Database / service credentials (#144 scrubbed names).
      'ROADIE_DB_URL',
      'ROADIE_DB_AUTH_TOKEN',
      'ROADIE_DB_AUTH_TOKEN_FILE',
      'ROADIE_SERVICE_TOKEN_FILE',
      // The token-minting secret must never reach a shell.
      'ROADIE_AGENT_TOKEN_SECRET',
      // Server-process state that would let a shell act as the bot.
      'ROADIE_DATA_DIR',
      'ROADIE_LOCK_PORT',
      'ROADIE_OPENCODE_PROCESS',
      // Provider keys.
      'ANTHROPIC_API_KEY',
      'OPENAI_API_KEY',
      'OPENROUTER_API_KEY',
      'Z_AI_API_KEY',
    ]
    for (const name of forbidden) {
      expect(script).not.toContain(name)
    }
  })

  test('forwards exactly the #144 attribution, session and agent token names', async () => {
    const { AGENT_TOKEN_ENV } = await import('./agent-token.js')
    const { ROADIE_SESSION_ID_ENV } = await import('./bash-tool-schema-plugin.js')
    const { TURN_ATTRIBUTION_ENV_NAMES } = await import('./turn-attribution-env.js')
    expect(ISOLATED_SHELL_FORWARD_ENV_NAMES).toContain(AGENT_TOKEN_ENV)
    expect(ISOLATED_SHELL_FORWARD_ENV_NAMES).toContain(ROADIE_SESSION_ID_ENV)
    for (const name of TURN_ATTRIBUTION_ENV_NAMES) {
      expect(ISOLATED_SHELL_FORWARD_ENV_NAMES).toContain(`ROADIE_${name}`)
    }
    // The allowlist is exactly the fixed names plus the #144 contract names.
    expect(ISOLATED_SHELL_FORWARD_ENV_NAMES).toHaveLength(2 + TURN_ATTRIBUTION_ENV_NAMES.length)
  })

  test('uses a fixed PATH, not the inherited one', () => {
    const script = buildIsolatedShellScript(wrapperInput)
    expect(script).toContain(`PATH='${ISOLATED_SHELL_PATH}'`)
  })

  test('single-quote escapes agent-controlled values', () => {
    const script = buildIsolatedShellScript({
      ...wrapperInput,
      account: { ...account, home: "/home/o'brien" },
    })
    expect(script).toContain(`HOME='/home/o'\\''brien'`)
  })
})

describe('checkShellIsolationPrivileges', () => {
  const linux = 'linux' as const

  test('root passes without capabilities', () => {
    expect(
      checkShellIsolationPrivileges({
        effectiveUid: 0,
        effectiveCapabilities: '0000000000000000',
        platform: linux,
      }),
    ).toBe(true)
  })

  test('CAP_SETUID + CAP_SETGID pass for a non-root euid', () => {
    const capEff = SETUID_SETGID_CAPABILITY_MASK.toString(16).padStart(16, '0')
    expect(
      checkShellIsolationPrivileges({
        effectiveUid: 1000,
        effectiveCapabilities: capEff,
        platform: linux,
      }),
    ).toBe(true)
  })

  test('a non-root euid without the capability bits fails with a clear message', () => {
    const result = checkShellIsolationPrivileges({
      effectiveUid: 1000,
      effectiveCapabilities: '0000000000000001',
      platform: linux,
    })
    expect(result).toBeInstanceOf(Error)
    expect((result as Error).message).toContain('CAP_SETUID')
    expect((result as Error).message).toContain('CAP_SETGID')
  })

  test('unavailable CapEff fails closed for a non-root euid', () => {
    expect(
      checkShellIsolationPrivileges({
        effectiveUid: 1000,
        effectiveCapabilities: null,
        platform: linux,
      }),
    ).toBeInstanceOf(Error)
  })

  test('non-linux platforms fail with the setpriv reason', () => {
    const result = checkShellIsolationPrivileges({
      effectiveUid: 0,
      effectiveCapabilities: '000001ffffffffff',
      platform: 'darwin',
    })
    expect(result).toBeInstanceOf(Error)
    expect((result as Error).message).toContain('setpriv')
  })
})

describe('parseCapEffHex', () => {
  test('parses wide kernel capability masks', () => {
    expect(parseCapEffHex('000001ffffffffff')).toBe(0x1ffffffffff)
    expect(parseCapEffHex('a8c0')).toBe(0xa8c0)
    expect(parseCapEffHex('0')).toBe(0)
  })

  test('rejects unparsable values', () => {
    expect(parseCapEffHex('')).toBeNull()
    expect(parseCapEffHex('nothex')).toBeNull()
  })

  test('the mask covers exactly CAP_SETUID (7) and CAP_SETGID (6)', () => {
    expect(SETUID_SETGID_CAPABILITY_MASK).toBe((1 << 7) | (1 << 6))
  })
})

describe('resolveIsolationBinary', () => {
  test('fails fast for a binary that is not on PATH', async () => {
    const result = await resolveIsolationBinary({ name: 'roadie-isolated-shell-missing-binary' })
    expect(result).toBeInstanceOf(Error)
    expect((result as Error).message).toContain('roadie-isolated-shell-missing-binary')
  })

  test('resolves an absolute path for a binary that exists', async () => {
    const result = await resolveIsolationBinary({ name: 'sh' })
    if (result instanceof Error) throw new Error(`expected sh to resolve, got: ${result.message}`)
    expect(result.startsWith('/')).toBe(true)
  })
})

describe('writeIsolatedShellWrapper', () => {
  test('writes an executable 0755 wrapper under <dataDir>/bin/isolated-shell/bash', () => {
    const dataDir = useTempDir()
    const result = writeIsolatedShellWrapper({ dataDir, script: '#!/bin/bash\nexit 0\n' })
    expect(typeof result).toBe('string')
    const wrapperPath = path.join(dataDir, 'bin', 'isolated-shell', 'bash')
    expect(fs.existsSync(wrapperPath)).toBe(true)
    expect(fs.statSync(wrapperPath).mode & 0o777).toBe(0o755)
    expect(fs.readFileSync(wrapperPath, 'utf8')).toBe('#!/bin/bash\nexit 0\n')
  })

  test('rewrites in place when the script changes and keeps the mode', () => {
    const dataDir = useTempDir()
    const first = writeIsolatedShellWrapper({ dataDir, script: 'one' })
    expect(first).toBe(path.join(dataDir, 'bin', 'isolated-shell', 'bash'))
    const second = writeIsolatedShellWrapper({ dataDir, script: 'two' })
    expect(second).toBe(first)
    expect(fs.readFileSync(path.join(dataDir, 'bin', 'isolated-shell', 'bash'), 'utf8')).toBe('two')
    expect(fs.statSync(path.join(dataDir, 'bin', 'isolated-shell', 'bash')).mode & 0o777).toBe(0o755)
  })
})

describe('evaluateIsolatedShellAccess', () => {
  const agentUid = 4242
  const agentGid = 4242

  test('a shared-group setgid project directory passes', () => {
    const problems = evaluateIsolatedShellAccess({
      agentUid,
      agentGid,
      entries: [
        { path: '/srv/project', expectation: 'agent-read-write', uid: 0, gid: agentGid, mode: 0o402770 },
      ],
    })
    expect(problems).toEqual([])
  })

  test('a root-owned 0755 project directory fails with the setgid recipe', () => {
    const problems = evaluateIsolatedShellAccess({
      agentUid,
      agentGid,
      entries: [
        { path: '/srv/project', expectation: 'agent-read-write', uid: 0, gid: 0, mode: 0o40755 },
      ],
    })
    expect(problems).toHaveLength(1)
    expect(problems[0]).toContain('/srv/project')
    expect(problems[0]).toContain('chmod 2770')
  })

  test('a private root-owned data dir passes the denied expectation', () => {
    const problems = evaluateIsolatedShellAccess({
      agentUid,
      agentGid,
      entries: [
        { path: '/home/me/.roadie', expectation: 'agent-denied', uid: 0, gid: 0, mode: 0o40700 },
      ],
    })
    expect(problems).toEqual([])
  })

  test('a group- or world-readable private path fails', () => {
    const problems = evaluateIsolatedShellAccess({
      agentUid,
      agentGid,
      entries: [
        { path: '/home/me/.roadie', expectation: 'agent-denied', uid: 0, gid: agentGid, mode: 0o40750 },
        { path: '/usr/share/opencode', expectation: 'agent-denied', uid: 0, gid: 0, mode: 0o40755 },
      ],
    })
    expect(problems).toHaveLength(2)
    expect(problems[0]).toContain('chmod 700')
    expect(problems[1]).toContain('chmod 700')
  })

  test('an agent-owned private path still fails the denied expectation', () => {
    const problems = evaluateIsolatedShellAccess({
      agentUid,
      agentGid,
      entries: [
        { path: '/home/roadie-agent/secret', expectation: 'agent-denied', uid: agentUid, gid: agentGid, mode: 0o40700 },
      ],
    })
    expect(problems).toHaveLength(1)
  })
})

describe('checkIsolatedShellSetup', () => {
  test('confirms agent-writable projects and agent-denied private paths', () => {
    const root = useTempDir()
    const dataDir = path.join(root, 'data')
    const projectDirectory = path.join(root, 'project')
    fs.mkdirSync(dataDir, { mode: 0o700 })
    fs.chmodSync(dataDir, 0o700)
    fs.mkdirSync(projectDirectory, { recursive: true })
    fs.chmodSync(projectDirectory, 0o777)

    // The agent account is synthetic (4242), so the runner's uid/gid stand in
    // for "root": the project dir is world-writable (agent can use it), the
    // data dir is private to the runner (agent cannot read it). Denied paths
    // are injected so the check never depends on the runner's real home.
    const problems = checkIsolatedShellSetup({
      dataDir,
      projectDirectories: [projectDirectory],
      account,
      deniedPaths: [dataDir, path.join(dataDir, 'credentials')],
    })
    expect(problems).toEqual([])

    // An agent-readable private path (a world-readable dir inside dataDir)
    // and an agent-unwritable project are both reported.
    const leaked = path.join(dataDir, 'leaked')
    fs.mkdirSync(leaked, { mode: 0o755 })
    fs.chmodSync(leaked, 0o755)
    const lockedProject = path.join(root, 'locked-project')
    fs.mkdirSync(lockedProject, { mode: 0o755 })
    fs.chmodSync(lockedProject, 0o755)
    const problemsMixed = checkIsolatedShellSetup({
      dataDir,
      projectDirectories: [projectDirectory, lockedProject],
      account,
      deniedPaths: [dataDir, leaked],
    })
    expect(problemsMixed).toHaveLength(2)
    // Project entries are evaluated before denied paths.
    expect(problemsMixed[0]).toContain(lockedProject)
    expect(problemsMixed[1]).toContain(leaked)
  })

  test('skips missing paths instead of failing', () => {
    const root = useTempDir()
    const problems = checkIsolatedShellSetup({
      dataDir: path.join(root, 'does-not-exist'),
      projectDirectories: [path.join(root, 'also-missing')],
      account,
      deniedPaths: [path.join(root, 'private-missing')],
    })
    expect(problems).toEqual([])
  })
})

describe('resolveAgentAccount', () => {
  test('refuses a uid 0 account: dropping to root isolates nothing', async () => {
    const account = await resolveAgentAccount({ username: 'root' })
    expect(account).toBeInstanceOf(Error)
    if (account instanceof Error) expect(account.message).toContain('unprivileged')
  })

  test('a missing user is a clear error', async () => {
    const account = await resolveAgentAccount({ username: 'roadie-no-such-user-xyz' })
    expect(account).toBeInstanceOf(Error)
    if (account instanceof Error) expect(account.message).toContain('does not exist')
  })
})
